# Change these first
owner:  # Your GitHub username
repo: ServiceUptimeSTG # Your GitHub repository name
sites:
  - name: Hexabase Staging Login
    url: https://az.hexabase.com/login
  - name: Hexabase Staging API
    url: https://az-api.hexabase.com/health_check
  - name: Community Site
    url: https://community.hexabase.com
  - name: Apicore Service
    url: https://az-hxg.hexabase.com/apicore/health_check
    method: GET
  - name: LinkerAPI Service
    url: https://az-hxg.hexabase.com/linkerapi/health_check
    method: GET
assignees: # Users to assign downtime issues (optional)
  - Hokutosei    
status-website:
  baseUrl: /ServiceUptimeSTG
  name: Service Uptime
